spring:
  # 데이터 베이스 설정
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  # JPA 설정
  jpa:
    hibernate:
      ddlAuto: create

# 파일 업로드 경로
file:
  upload.path: D:/uploads/
  upload.url: /uploads/